### ISSUE TITLE
Create report route

### ISSUE THREAD

**Issue by eranshmil** [botim/backend#10]
The route request:
```ts
{
  userId: string,
  postId: string,
  commentId: string,
  replyCommentId: string,
  platform: enum<TWITTER, FACEBOOK, INSTAGRAM>,
  reasons: enum<BOT, VIOLENCE, FAKE>[],
  description: string,
  reporterKey: string
}
```

200 response if it went well.

**Comment by mderazon** [comment]
What happens when reported ? Just store in db ?

**Comment by eranshmil** [comment]
@haimkastner Please add the missing columns: `postId`, `commentId`, `replyCommentId`.

Also, please use snake-case for table names and columns. :)
