### ISSUE TITLE
Change API according to Eran's request

### ISSUE THREAD

**Issue by dafnarosenblum** [botim/backend#5]
Replace the get route with a route that receives a list of ids and returns the once that are bots - from the given list.

**Comment by eranshmil** [comment]
The request should be something like that:
```ts
{
  userIds: number[],
  loggedInUserId: number
}
```

The route will do the following:
1. Check the statuses of each of the `userIds`.
1. Check whether the loggedin user is a team member.

The response should be something like that:
```ts
{
  isTeamMember: boolean,
  userStatuses: { [userId: number]: Status }[]
}
```

**Comment by mderazon** [comment]
I can help with that.
What's the use case for this endpoint ? I'm asking because it's usually discouraged having a body in GET requests and on the other hand, making it a POST loses the semantic meaning of this endpoint.

If we can get by on putting this in query param that would be better.
Something like
```
GET /bots?q=userid1,userid2,userid3,...
```

In the future you might want to filter by other things as well
```
GET /bots?q=userid1,userid2&isTeamMember=false
```

But if the list of users you query for is really big, it will surpass the url limit (2,083 characters)

**Comment by eranshmil** [comment]
I think that we won't reach that limit in the query string.
But, the `isTeamMember` is part of the response, not a filtering option.

The query string should accept two params: `userIds` and `loggedInUserId `.

**Comment by mderazon** [comment]
Okay, so i'll put it in the query, loggedInUserId should not be in the query param though, should come from any sort of authentication, probably in the header once we have this: botimonline/botsBackend#1

So maybe i'll work on botimonline/botsBackend#1 first

**Comment by eranshmil** [comment]
This is not the meaning of the param, just a bad naming. :)
It suppose to be the twitter user id, so it will check if he is part of the team, and show him some indication in the page that the extension is still working as expected.

**Comment by liorn** [comment]
@eranshmil I can take this.
A couple of (n00b?) questions, just want to make sure we're synced...

1. Right now, how do we know who's a team member? Should I create a new DB table which holds team member IDs? (and then we fill it with another tool, not from the extension itself)?
2. Can I open a new route for it? Or should I reuse "confirmed"?

**Comment by eranshmil** [comment]
There is two issues to complete before this one.
#7 and #8.
